#!/usr/bin/env bash
# Install nginx and start the service


apt-get update
apt-get install -y nginx


echo "<!DOCTYPE html><html><head><title>Hello World!</title></head><body><h1>Hello World!</h1></body></html>" > /var/www/html/index.html


service nginx start

