#!/usr/bin/env bash

# Install Nginx
apt-get update
apt-get install -y nginx


echo "<!DOCTYPE html><html><head><title>Redirecting...</title><meta http-equiv=\"refresh\" content=\"0; URL='https://www.youtube.com/watch?v=QH2-TGUlwu4'\" /></head></html>" > /var/www/html/redirect_me.html


echo "server {
    listen 80;
    server_name _;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    location / {
        root /var/www/html;
        index index.html;
    }
}" > /etc/nginx/sites-available/default


service nginx restart


