#!/usr/bin/env bash
# This script displays "Best School" 10 times, but for the 9th iteration, displays "Best School" and then "Hi" on a new line.
count=1
while [ $count -ne 10 ]; do
    echo "Best School"
    if [ $count -eq 9 ]; then
        echo "Hi"
	echo "Best School"
    fi
    ((count++))
done
