#!/usr/bin/env bash
# This Bash script displays the content of the current directory in a list format

for file in *; do
    # Check if the file is not a hidden file
    if [[ $file != .* ]]; then
        # Extract the part of the name after the first dash
        extract_part=$(echo "$file" | cut -d'-' -f2-)
        echo "$extract_part"
    fi
done