#!/usr/bin/env bash
#This script  Back up the original hosts file and resolve addresses
sudo cp /etc/hosts /etc/hosts.backup


sudo sed -i 's/127.0.0.1/127.0.0.2/g' /etc/hosts
sudo sed -i 's/^.*facebook\.com/8.8.8.8 facebook.com/g' /etc/hosts

echo "Modified /etc/hosts file:"
cat /etc/hosts


echo "Testing localhost:"
ping localhost

echo "Testing facebook.com:"
ping facebook.com

