#!/usr/bin/env bash
# Uses ssh to connect to server using the private key ~/.ssh/school with the user ubuntu
ssh -i ~/.ssh/school -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=ERROR -o PasswordAuthentication=no -o ConnectTimeout=5 -o ConnectionAttempts=3 -o BatchMode=yes ubuntu@54.165.249.210

